release:
  branching:
    execution:
      time: "20:00:00"
    schedule:
      - on: "2024-06-28"
        name: release/0.52
        initial-tag:
          create: true
          name: v0.52.0-alpha.2

